//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace klassycafe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class klassycafeEntities : DbContext
    {
        public klassycafeEntities()
            : base("name=klassycafeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHEF> CHEF { get; set; }
        public virtual DbSet<MENUCATEGORY> MENUCATEGORY { get; set; }
        public virtual DbSet<MENUITEM> MENUITEM { get; set; }
        public virtual DbSet<RESERVATION> RESERVATION { get; set; }
        public virtual DbSet<RESERVATIONSTATE> RESERVATIONSTATE { get; set; }
        public virtual DbSet<STATE> STATE { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<USER> USER { get; set; }
        public virtual DbSet<CONTACT> CONTACT { get; set; }
    }
}
